# Generated by Django 4.2.4 on 2023-08-23 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_remove_filmwork_certificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
    ]
