# Generated by Django 4.2.4 on 2023-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_rename_created_personfilmwork_created_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "genre"), name="unique_filmwork_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "person", "role"),
                name="unique_filmwork_person_role",
            ),
        ),
        migrations.AlterModelTable(
            name="filmwork",
            table='content"."film_work',
        ),
    ]
