# Generated by Django 4.2.4 on 2023-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_person_personfilmwork_person_film_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="certificate",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="certificate"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="movies/", verbose_name="file"
            ),
        ),
    ]
