# Generated by Django 4.2.4 on 2023-08-23 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_created_filmwork_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmwork",
            name="certificate",
        ),
    ]
