version: '3.9'

services:
  web:
    build: .
    volumes:
      - static_volume:/opt/app/static/
    ports:
      - 8182:8000
    env_file:
      - ./app/config/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etc/postgres/default-init.sql:/docker-entrypoint-initdb.d/default-init.sql
    env_file:
      - ./app/config/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", 'movies_database' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  static_volume:
